############ DO NOT CHANGE THESE ################
INCDIR:=.:%/Prelude:%/Libraries:src
TOP_MODULE:=mk_sample_design

############# User changes to be done below #################
TOP_DIR:=./src
TOP_FILE:=sample_design.bsv
